//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_APIC2CDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rating
    {
        public int RatingID { get; set; }
        public string RatingUserrating { get; set; }
        public string RatingUserrated { get; set; }
        public double RatingPoint { get; set; }
        public System.DateTime RatingDate { get; set; }
    }
}
